Review
ShunaevN/blog-customizer pull request #1
Opened 2024-05-19 18:32 UTC by ShunaevN

2024-05-19 21:09 UTC, olgalatkina requested changes
Здравствуйте.

**У вас получилась хорошая работа:**
- Почти полностью реализован функционал.
- Для условного добавления css-классов спользуется библиотека `clsx`.

**Но есть несколько моментов, которые надо поправить:**
- [x] Проект не соответствует макету: 
    - Расстояние между элементами формы должно быть 50px. Чтобы управлять отступами между элементами формы лучше использовать свойство `gap`.
     - Размер заголовков элементов формы не соответствует макету.
     - У выбраного размера шрифта должна подсвечиваться кнопка. Используйте компонент `RadioGroup`
- [ ] На небольших экранах нет возможности сохранить выбранные настройки или выбрать фиолетовый цвет фона. Нужно поправить стили у сайдбара и формы.
- [ ] По названию должно быть понятно, что хранится в стейте.
- [ ] Достаточно тех типов, что есть в файле `constants/articleProps.ts`.
- [ ] Не допускается использовать для значения по умолчанию элементы с нулевым индексом из массивов свойств.
- [ ] Нет необходимости создавать дополнительные функции обработчики.
- [ ] Обработчик сохранения данных лучше вызывать при отправке формы. Код должен быть в одной функции.
- [ ] Обработчик закрытия сайдбара по клику вне сайдбара не должен висеть всегда на документе, его нужно вешать в момент открытия и удалять в момент закрытия. 

**Правки можно лучше остаются на ваше усмотрение:**
- [ ] Для одиночных селекторов не стоит использовать библиотеку clsx.
- [ ] Стоит вынести компонент App в отдельный файл.
- [ ] Для закрытия сайдбара по клику вне сайдбара попробуйте использовать кастомный хук.

Успешного рефакторинга!

2024-05-19 21:09 UTC, olgalatkina commented on src/components/arrow-button/ArrowButton.module.scss
> +	transform: translate(600px);
**Надо исправить:**
Это не способ пофиксить баг с кнопкой. Нужно вернуть 616px.

2024-05-19 21:09 UTC, olgalatkina commented on src/components/arrow-button/ArrowButton.tsx
> +			className={clsx(styles.container, isOpen && styles.container_open)}>
**Отлично:**
Замечательно, что используете библиотеку `clsx` для условного добавления стилей.

2024-05-19 21:09 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.module.scss
> +	overflow: hidden;
**Надо исправить:**
На небольших экранах (ноутбук) нет доступа к кнопкам и нет возможности выбрать например фиолетовый цвет фона:  https://yadi.sk/d/q0KiwcQI-Q5Imw, https://yadi.sk/d/m7jviApOjVlCAA. 

**Можно лучше:**
Попробуйте найти другое решение. Здесь можно прочитать подробности про `overflow`: https://doka.guide/css/overflow/
Проблема возникает из-за фиксированной ширины формы, значит её и надо решать: поменяем у класса `.form` одно свойство:
```
width: 100%;
```
Останется прописать правильное значение `overflow`.

2024-05-19 21:09 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.module.scss
> +	width: 602px;
**Надо исправить:**
Выше комментарий как лучше исправить значение.

2024-05-19 21:09 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.module.scss
> +	justify-content: space-between;
**Надо исправить:**
Для управления расстоянием между элементами формы лучше воспользоваться свойством `gap`.
При этом все лишние дивы из разметки надо удалить.

2024-05-19 21:09 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.tsx
> +					<div style={{ height: '50px' }}></div>
**Надо исправить:**
Чтобы управлять отступами между элементами формы лучше использовать свойство `gap`.
Все подобные дивы надо удалить.

2024-05-19 21:09 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.tsx
> +				<form className={styles.form} onSubmit={handleSubmit}>
**Отлично:**
Отлично, что обработчик сохранения данных вызывается при отправке формы.

2024-05-19 21:09 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.tsx
> +					<div className={clsx(styles.bottomContainer)}>
**Можно лучше:**
Для одиночных селекторов не стоит использовать библиотеку `clsx`/
Замечание относится ко всему проекту.

2024-05-19 21:09 UTC, olgalatkina commented on src/index.tsx
> +	const [formParamsState, setFormParamsState] = useState(defaultArticleState);
**Надо исправить:** 
По чеклисту - “имена переменных — существительные, отражающие то, что в них хранится”. По названию должно быть понятно, что хранится в стейте. Имя `formParamsState` вводит в заблуждение. Это состояние статьи или страницы.

2024-05-19 21:09 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.tsx
> +type FormParamsStatePropsType = {
**Можно лучше:**
Общепринятым является написать тип, используя имя компонента, добавив постфикс `Props`:
```
ArticleParamsFormProps
```

2024-05-19 21:09 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.tsx
> +type formParamsType = {
**Надо исправить:**
Не стоит создавать лишних сущностей. Достаточно тех типов, что есть в файле `constants/articleProps.ts`.
Замечание так же относится к типу `ValuesType`.

2024-05-19 21:09 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.tsx
> +	const [font, setFont] = useState(fontFamilyOptions[0]);
**Надо исправить:** 
Настройки статьи по умолчанию описаны в объекте `defaultArticleState`  в файле `constants/articleProps.ts` стартеркита. В проекте нужно использовать значения из этого объекта как настройки по умолчанию, как для самой статьи, так и как начальные значения полей форм.
Не допускается использовать для значения по умолчанию элементы с нулевым индексом из массивов свойств. То что настройки по умолчанию имеют именно нулевой индекс можно считать просто совпадением и это может измениться в любой момент.

2024-05-19 21:09 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.tsx
> +	const handleChangeFont = (selected: OptionType) => {
**Надо исправить:**
Нет необходимости создавать дополнительные функции обработчики если они сами по себе ничего не делают, можно использовать просто функции сеттеры возвращаемые `useState`:
```
onChange={setFont}
```

2024-05-19 21:09 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.tsx
> +					<Text weight={800} size={18} uppercase={true}>
**Надо исправить:**
Для выбора размера шрифта подойдёт компонент `RadioGroup`

2024-05-19 21:09 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.tsx
> +	const setAllValues = (values: ValuesType) => {
**Надо исправить:**
У вас уже есть функция `handleSubmit`. Используйте именно её для того, чтобы сохранять новые настройки статьи.
Нужно перенести код в функцию `handleSubmit`. Объект `values` не понадобится.

2024-05-19 21:09 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.tsx
> +	const handleSubmitform = () => {
**Надо исправить:**
Абсолютно лишняя сущность. Три функции для одного маленького сабмита - это перебор=)

2024-05-19 21:09 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.tsx
> +							onClick={handleSubmitform}
**Надо исправить:** 
У вас уже есть обработчик события `submit`, этого достаточно.
Обработчик сохранения данных должен вызываться при отправке формы и достаточно обработать только событие отправки формы. Не нужно вешать его на кнопку.

2024-05-19 21:09 UTC, olgalatkina commented on src/index.tsx
>  const App = () => {
**Можно лучше:**
Обычно корневой `index.tsx` держат максимально компактным. Стоит вынести компонент `App` в отдельный файл в папке `components/app/App.tsx`.

2024-05-19 21:09 UTC, olgalatkina commented on src/components/select/Select.tsx
> +					<Text size={18} weight={800} uppercase>
**Надо исправить:**
Нет необходимости исправлять библиотечный компонент. Он соответствует макету: https://yadi.sk/d/zLNSz5zuM2W1Gw

2024-05-19 21:09 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.tsx
> +	useEffect(() => {
**Надо исправить:** 
Обработчик не должен висеть всегда на документе, его нужно вешать в момент открытия и удалять в момент закрытия. Нет необходио отслеживать событие, если сайдбар закрыт. Поэтому необходимо указать массив зависимостей хука `useEffect` и **добавить внутри проверку, что сайдбар открыт**.

**Можно лучше:**
Попробуйте вынести функционал закрытия сайдбара по клику вне сайдбара в кастомный хук.

2024-05-20 16:46 UTC, ShunaevN commented on src/components/article-params-form/ArticleParamsForm.module.scss
> +	justify-content: space-between;
gap установил, div удалил, но это свойство оставил для позиционирования заголовка формы и кнопок сброса и сабмита

2024-05-20 17:01 UTC, ShunaevN commented on src/components/article-params-form/ArticleParamsForm.tsx
> +type formParamsType = {
заменил на ArticleStateType

2024-05-21 09:02 UTC, closed without merging